WIP - First setup tutorials
MountebankSwift/MountebankSwift pull request #44
Opened 2024-05-24 21:24 UTC by teameh

Still work in progress :)

2024-05-30 15:31 UTC, mat1th requested changes

2024-05-30 15:31 UTC, mat1th commented on Sources/MountebankSwift/Documentation.docc/Tutorials/integration.tutorial
> +                Using our terminal, we'll install Mountebank. If you don't have ``npm`` installed, you can install it with brew using ``$ brew install node``
Could you use single `? Now it is trying to resolve a code reference.

2024-05-30 15:31 UTC, mat1th commented on Sources/MountebankSwift/Documentation.docc/Tutorials/integration.tutorial
> +                We change it so it uses the launch environment ``listApiHost`` during UI testing.
same here. Use single `. because `listApiHost` is not part of MountebankSwift it self.

2024-05-30 15:31 UTC, mat1th commented on Sources/MountebankSwift/Documentation.docc/Tutorials/mountebank-overview.tutorial
> +                Mountebank will create stub servers for us called "Imposters".
Maybe also reference mountebank docs?

2024-05-30 15:31 UTC, mat1th commented on Sources/MountebankSwift/Documentation.docc/Tutorials/tutorial-table.tutorial
> +<!--    @Chapter(name: "UI Testing and Network Mocking") {-->
could you the remove commented code.

2024-05-30 15:31 UTC, mat1th commented on Sources/MountebankSwift/Documentation.docc/Tutorials/uitesting-refresher.tutorial
> +@Tutorial {
This tutorial is empty. Could you remove it? So we can merge the other parts of the pr?

2025-07-07 08:11 UTC, teameh commented on Sources/MountebankSwift/Documentation.docc/Tutorials/mountebank-overview.tutorial
> +                Mountebank will create stub servers for us called "Imposters".
They're down now 😞

2025-07-07 08:11 UTC, teameh commented on Sources/MountebankSwift/Documentation.docc/Tutorials/uitesting-refresher.tutorial
> +@Tutorial {
Done

2025-07-08 06:26 UTC, merged